spring.application.name=backend

# Perfil activo
spring.profiles.active=dev

# Contexto de la API
server.servlet.context-path=/colegio/san-andres/api/v1

# Swagger
springdoc.swagger-ui.path=/docs

# Variables de entorno
spring.config.import=optional:file:.env[.properties]